config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :monthly_orders, param: :yyyymm
  resources :order
  root 'monthly_orders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :users, through: :order
  has_many :order
  accepts_nested_attributes_for :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
  has_many :item, through: :order
  has_many :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/monthly_orders_controller.rb
class MonthlyOrdersController < ApplicationController

  def index
    now = Date.today.strftime('%Y%m')
    redirect_to action: :show, yyyymm: now
  end
  
  def show
    now = Date.strptime(params[:yyyymm]+"01",'%Y%m%d')
    @lastmonth = now.last_month.strftime("%Y%m")
    @nextmonth = now.next_month.strftime("%Y%m")
    @row_headers = (now.beginning_of_month.to_date)..(now.end_of_month.to_date)
    @column_headers = Item.select(:name, :price).order(:id)
    monthlyorders = Order.where('user_id = ? and date >= ? and date <= ? ',
                         current_user.id, now.at_beginning_of_month.to_date, now.end_of_month.to_date).count
    if monthlyorders == 0
      create_monthlyorders(params[:yyyymm])
    end
    @orders = Order.select(:id, :item_id, :date, :number)
                  .where('user_id = ? and date >= ? and date <= ? ',
                         current_user.id, now.at_beginning_of_month.to_date, now.end_of_month.to_date)
                  .order(:date, :item_id)
                  .group_by {|o| o[:date]}
  end

  def create_monthlyorders(yyyymm)
    month = Date.strptime(yyyymm+"01",'%Y%m%d')
    (month.beginning_of_month.to_date..month.end_of_month.to_date).each do |days|
      Order.transaction do
        Item.all.each do |item|
          Order.create!(
            [
              {
                date: days,
                number: 0,
                item_id: item.id,
                user_id: current_user.id
              }
            ]
          )
        end
      end
    end   
  end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  def update
    order = Order.find(params[:id])
    order.update(number: params[:order][:number])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @orders = Order.order("id")
  end

  def about
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # callback for facebook
  # def facebook
  #   callback_for(:facebook)
  # end

  # # callback for twitter
  # def twitter
  #   callback_for(:twitter)
  # end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      # set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "Bento"
    title = @page_title + " - " + title if @page_title
    title
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/monthly_orders_helper.rb
module MonthlyOrdersHelper
  def edit_month(month)
    Date.strptime(month + '01', '%Y%m%d').strftime('%Y-%m')
  end

  def past?(target_day)
    target_day <= Date.today
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>
    <%= page_title %>
  </title>
  <meta name="viewport" content="width=device-width,user-scalable=no,maximum-scale=1" />

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'shared/navbar' %>
  <%= yield %>

  </div>
</body>

</html>

app/views/monthly_orders/index.html.erb
<% @page_title = "Order" %>
<h1>
  <%= @page_title %><br>
  <%= current_user.email %>
</h1>
<table class="list">
  <tr>
    <th>注文日</th>
    <% @column_headers.each.with_index do |column_header| %>
    <th>
      <%= column_header.name %><br>
      <%= column_header.price %>円
    </th>
    <% end %>
  </tr>
  <% @row_headers.each do |target_day| %>
  <tr>
    <td>
      <%= target_day %>
    </td>
    <% (@orders[target_day]).each do |order| %>
    <td>
      <%= form_with model: order, id: order[:id] do |f| %>
      <%= f.number_field :number %>
      <%= f.submit %>
      <% end %>
      <%# <%= @monthly_lists[i][n] %>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/monthly_orders/show.html.erb
<%= link_to monthly_order_path(@lastmonth) do %>
<i class="fa fa-chevron-circle-left" aria-hidden="true"></i>
<% end %>
<%= edit_month(params[:yyyymm]) %>
<%= link_to monthly_order_path(@nextmonth) do %>
<i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>注文日</th>
      <% @column_headers.each.with_index do |column_header| %>
      <th>
        <%= column_header.name %>
        <%= column_header.price %>円
      </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @row_headers.each do |target_day| %>
    <tr>
      <td>
        <%= target_day %>
      </td>
      <% (@orders[target_day]).each do |order| %>
      <td>
        <%= form_with model: order, id: order[:id] do |f| %>
        <div class="form-row align-items-center">
          <div class="col-sm-7">
            <%#= f.number_field :number, in: 0...100, class: "form-control number_field", id: "number_field" + i.to_s %>
            <%= f.number_field :number, in: 0...100, class: "form-control", disabled: past?(target_day) %>
          </div>
          <div class="col-auto my-1">
            <%= button_tag(type: 'f.submit', class: "btn btn-primary", disabled: past?(target_day)) do %>
            <i class="fa fa-pencil" aria-hidden="true"></i>
            <% end %>
          </div>

          <% end %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<%# <script>
  $(function () {

    if ($('.number_field').val().length == 0) {
      $('.submit').prop("disabled", true);
    }
    $('.number_field').bind('keydown keyup keypress change', function (ev) {
      if ($(this).val().length > 0) {
        $('.submit').prop("disabled", false);
      } else {
        $('.submit').prop("disabled", true);
      }
    });
  });
</script> %>

app/views/shared/_error_messages.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
    <span class="sr-only">close</span>
  </button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
    <span class="sr-only">close</span>
  </button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">Bento</a>
  <div id="user-info">
    <% if user_signed_in? %>
    <%= link_to 'Sign out', destroy_user_session_path, class: "btn btn-outline-success my-2 my-sm-0", method: :delete  %>
    <% else %>
    <%= link_to "Sign in", user_google_oauth2_omniauth_authorize_path, class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/top/index.html.erb
<%  @page_title = "Order" %>
<h1><%= @page_title %></h1>

<% if @orders.present? %>
  <table class="list">
    <tr>
      <th>注文日</th>
      <th>商品名</th>
      <th>単価</th>
      <th>数量</th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.date %></td>
        <td><%= order.item.name %></td>
        <td><%= order.item.price %></td>
        <td><%= order.number %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>注文履歴がありません。</p>
<% end %>